require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TutorsController do

  # This should return the minimal set of attributes required to create a valid
  # Tutor. As you add validations to Tutor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TutorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tutors as @tutors" do
      tutor = Tutor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tutors).should eq([tutor])
    end
  end

  describe "GET show" do
    it "assigns the requested tutor as @tutor" do
      tutor = Tutor.create! valid_attributes
      get :show, {:id => tutor.to_param}, valid_session
      assigns(:tutor).should eq(tutor)
    end
  end

  describe "GET new" do
    it "assigns a new tutor as @tutor" do
      get :new, {}, valid_session
      assigns(:tutor).should be_a_new(Tutor)
    end
  end

  describe "GET edit" do
    it "assigns the requested tutor as @tutor" do
      tutor = Tutor.create! valid_attributes
      get :edit, {:id => tutor.to_param}, valid_session
      assigns(:tutor).should eq(tutor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tutor" do
        expect {
          post :create, {:tutor => valid_attributes}, valid_session
        }.to change(Tutor, :count).by(1)
      end

      it "assigns a newly created tutor as @tutor" do
        post :create, {:tutor => valid_attributes}, valid_session
        assigns(:tutor).should be_a(Tutor)
        assigns(:tutor).should be_persisted
      end

      it "redirects to the created tutor" do
        post :create, {:tutor => valid_attributes}, valid_session
        response.should redirect_to(Tutor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tutor as @tutor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tutor.any_instance.stub(:save).and_return(false)
        post :create, {:tutor => {  }}, valid_session
        assigns(:tutor).should be_a_new(Tutor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tutor.any_instance.stub(:save).and_return(false)
        post :create, {:tutor => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tutor" do
        tutor = Tutor.create! valid_attributes
        # Assuming there are no other tutors in the database, this
        # specifies that the Tutor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tutor.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => tutor.to_param, :tutor => { "these" => "params" }}, valid_session
      end

      it "assigns the requested tutor as @tutor" do
        tutor = Tutor.create! valid_attributes
        put :update, {:id => tutor.to_param, :tutor => valid_attributes}, valid_session
        assigns(:tutor).should eq(tutor)
      end

      it "redirects to the tutor" do
        tutor = Tutor.create! valid_attributes
        put :update, {:id => tutor.to_param, :tutor => valid_attributes}, valid_session
        response.should redirect_to(tutor)
      end
    end

    describe "with invalid params" do
      it "assigns the tutor as @tutor" do
        tutor = Tutor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tutor.any_instance.stub(:save).and_return(false)
        put :update, {:id => tutor.to_param, :tutor => {  }}, valid_session
        assigns(:tutor).should eq(tutor)
      end

      it "re-renders the 'edit' template" do
        tutor = Tutor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tutor.any_instance.stub(:save).and_return(false)
        put :update, {:id => tutor.to_param, :tutor => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tutor" do
      tutor = Tutor.create! valid_attributes
      expect {
        delete :destroy, {:id => tutor.to_param}, valid_session
      }.to change(Tutor, :count).by(-1)
    end

    it "redirects to the tutors list" do
      tutor = Tutor.create! valid_attributes
      delete :destroy, {:id => tutor.to_param}, valid_session
      response.should redirect_to(tutors_url)
    end
  end

end
